print('\n')
print("Hello World!!")
print('\n')
print('Did you know that I am coming for you??')
print('\n')
print('Yes, you!')

print("--------    -------      -------     -------      |     --------")
print("   |        |            |           |            |     |")
print("   |        |______      |______     |______      |     |------")
print("   |        |                  |           |      |     |")
print("___|        |______      ______|     ______|      |     |_______")